Feature/dough staking UI
pie-dao/pools.piedao.org pull request #185
Opened 2021-07-21 09:15 UTC by Chiptuttofuso

##### Description

##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

##### Testing

##### Refers/Fixes

2021-07-26 15:01 UTC, Alexintosh commented
## Notes

- Cursor pointer on buttons
- Boost to max is a big deal, we need to celebrate that with cool animations!
- accountWithdrawableRewards coming from the graph is always 0

2021-08-02 13:25 UTC, Alexintosh approved these changes

2021-08-02 13:32 UTC, Alexintosh requested changes
linter is not passing

2021-08-02 13:39 UTC, Chiptuttofuso commented
> linter is not passing

i'm on it

2021-08-06 09:16 UTC, Alexintosh approved these changes

2021-09-28 15:22 UTC, closed without merging