Slice release november
pie-dao/pools.piedao.org pull request #261
Opened 2021-11-02 10:35 UTC by Chiptuttofuso

##### Description

##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

##### Testing

##### Refers/Fixes

2021-11-02 13:51 UTC, AdrianAddesso requested changes
1. Missing responsive KPI Options banner in /#/staking-simulator
2. Copy fix needed at /#/learn to replace 'DeFi is growing fast, better keepinb up to date' with 'DeFi is growing fast, better keeping up to date'
3. The Buy field on the Slice row is empty at /#/pies on desktop and populated with a '-' on mobile. Please assure the '-' is on both

2021-11-02 15:02 UTC, Chiptuttofuso commented
> 1. Missing responsive KPI Options banner in /#/staking-simulator
> 2. Copy fix needed at /#/learn to replace 'DeFi is growing fast, better keepinb up to date' with 'DeFi is growing fast, better keeping up to date'
> 3. The Buy field on the Slice row is empty at /#/pies on desktop and populated with a '-' on mobile. Please assure the '-' is on both

all done!

2021-11-02 16:05 UTC, AdrianAddesso approved these changes
requested changes succesfully implemented.
Approved

2021-11-05 21:03 UTC, Alexintosh approved these changes

2021-11-05 21:30 UTC, merged