PIE-564: updated text on dough staking campaign page
pie-dao/pools.piedao.org pull request #276
Opened 2021-11-09 16:37 UTC by Chiptuttofuso

##### Description

##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

##### Testing

##### Refers/Fixes

2021-11-10 09:43 UTC, AdrianAddesso requested changes
There's a typo: Distsributed

Please do change that whole sentece to 'Distributed in the first month!'

2021-11-10 09:51 UTC, Alexintosh requested changes

2021-11-10 09:51 UTC, Alexintosh commented on src/pages/DoughStakingCampaign.svelte
> +      Distsributed during the first month distribution!
typo

2021-11-11 13:22 UTC, AdrianAddesso requested changes
Still pending to update to:
'Distributed during the first month distribution!'
to
'Distributed in the first month!'

2021-11-15 09:52 UTC, Alexintosh approved these changes

2021-11-15 09:54 UTC, Alexintosh requested changes
I don't understand why we keep the 135000 text since it's over. More effort is required on this page to be updates.

2021-11-18 11:24 UTC, AdrianAddesso requested changes
Final copy update: see image as outcome example:
Title: Earn rewards in three easy steps
Body: Stake your DOUGH, vote on proposals and claim your monthly rewards. 250+ members joined in the first month! 
CTA: Stake DOUGH to start earning rewards


![image](https://user-images.githubusercontent.com/87126850/142406540-7e311e7e-ab84-467e-82a3-db34a14181e9.png)

2021-11-18 12:13 UTC, AdrianAddesso approved these changes
Changes approved

2021-11-18 12:54 UTC, dimarconicola approved these changes
Looks good to me

2021-11-18 12:55 UTC, dantop114 approved these changes
lgtm

2021-11-18 13:25 UTC, Alexintosh approved these changes

2021-11-18 13:31 UTC, merged