created claim UI for kpi options
pie-dao/pools.piedao.org pull request #281
Opened 2021-11-10 17:27 UTC by Chiptuttofuso

##### Description

##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

##### Testing

##### Refers/Fixes

2021-11-15 14:48 UTC, AdrianAddesso requested changes
1. Align lock lenght to the left
![image](https://user-images.githubusercontent.com/87126850/141787697-a2a0b422-f4cd-4826-8519-abd8d82e0974.png)

2. Copy Changes
1. Change Total distributed rewards for Total Distributed KPI Options
2. Keep Your Claimable KPI Options as is
3. Change Your Estimated UMA KPI Options for Your Estimated Payout

2021-11-15 15:56 UTC, AdrianAddesso approved these changes
All good. Approved

2021-11-17 13:42 UTC, dimarconicola approved these changes
Tested with custom network
- data shown are correct
- claim triggers metamask
- tx is casted
- kDOUGH is airdropped to my wallet
- my claimable balance goes to 0

2021-11-17 13:43 UTC, dimarconicola commented
@AdrianAddesso should we review the content before merging this PR?

2021-11-18 01:40 UTC, AdrianAddesso requested changes
1. Copy change: **Use your kDOUGH to redeem the DOUGH payout** for **Use your kDOUGH to redeem the veDOUGH payout**
2. please adjust the padding of the numbered steps to 24px so that the distance between the number and the text is closer to what the design shows (_leave the Mobile version as is, otherwise there will be overlapping_)
![image](https://user-images.githubusercontent.com/87126850/142334658-6d29c62a-216d-4d34-b09a-6e0f70155aca.png)

3. Join our discord box should link to http://discord.link/PieDAO

4. The share button should have the following functionality:
    a) User clicks on the button 'Share'-> URL is copied in the clipboard -> button text changes to 'Link Copied!'
   b) The URL to be copied is /#/dough-staking-campaign
![image](https://user-images.githubusercontent.com/87126850/142335264-4c871f41-c748-4c7b-871b-c23e9902f20a.png)

2021-11-18 10:08 UTC, Alexintosh commented on src/notifications.js
> +          tnx.emitter.emit('tnxConfirmed');
wrong event name: tnxConfirmed

2021-11-18 11:10 UTC, AdrianAddesso requested changes
Sorry, just found an issue on the mobile version.
When user opens the nav menu, the progress bar milestones text overlaps with the menu text
![image](https://user-images.githubusercontent.com/87126850/142404692-7f499aec-a4a9-4018-b786-6072023345f7.png)

2021-11-18 12:17 UTC, AdrianAddesso approved these changes
Changes approved

2021-11-18 12:31 UTC, dimarconicola approved these changes
+1

2021-11-18 15:08 UTC, merged