Feature/pie-548: eDOUGH Vesting UI
pie-dao/pools.piedao.org pull request #283
Opened 2021-11-22 16:35 UTC by Chiptuttofuso

##### Description

##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

##### Testing

##### Refers/Fixes

2021-11-22 19:08 UTC, AdrianAddesso requested changes
Screenshots for every point can be found here: https://www.notion.so/PR-283-feedback-9844a5dca6e54ff38e16f69421f11d62
1. Remove scrolling bar (vertical and horizontal, in desktop and mobile) and adjust size properly so it does not require it.
2. Align vest in veDough to the left, so the icons are aligned
3. If 'vest in Dough' is in the past, then show 'Claim now'
4. Capitalize the work 'vest'
5. Some dates are weird...ignore if hardcoded
6. In mobile, the page loads first the Farm Pools information, pulling the user down to the middle of the page
7. When clicking on 'Stake' the notification message is shown but its content exceeds it's lenght limit (this may be a non-issue)
8. Information modal updates:
    1. Move the closing X to the right
    2. Put PIP-67 between ()
    3. Remove the underling from the word 'eDough'
9. Missing the 'Add veDough to Metamask' button
10. When scrolling down on the list of positions, the table headers dissapear

2021-11-24 18:13 UTC, AdrianAddesso requested changes
**General**
1. Position status 'Ready' and 'Stake & Earn' should be not bold.

**Claiming process related**
1. Claim button should change to 'Claimed' and Dough amount taken to cero after claiming completion.
2. Get Dough and Get veDough totals to be zeroed-out after Claiming or Staking completion

2021-11-25 14:17 UTC, AdrianAddesso approved these changes
Approved

2021-11-25 14:42 UTC, dantop114 approved these changes

2021-11-25 14:57 UTC, merged