changed defi++ to prefer buy over mint
pie-dao/pools.piedao.org pull request #344
Opened 2022-06-03 14:40 UTC by jordaniza

I wanted to look at a clean way to add DEFI++ as an option to buy/sell in the main exchange modal.

Reviewing the codebase, the reason it does not appear is because the setting `preferMintOverBuy` is set to `true`

Changing this setting adds the token to the swap list on `Tokensswap.svelte` and `Exchange.svelte`, as we want. It also has the following effects on `Dashboard.svelte`:

- When opening up the list of products (Pies list on `Dashboard.svelte`), clicking the `buy` button links directly to the swap page, instead of to the DEFI++ page:

```svelte
                {#if pie.buyButton}
                  {#if pie.useMintOverBuy}
                      <a href={`#/pie/${pie.address}`}>
                        <button class="table-btn highlight-box min-w-70px">
                          {pie.symbol}
                        </button>
                      </a>
                  {:else}
                    <a href={`#/swap`}>
                      <button class="table-btn highlight-box min-w-70px">
                        {pie.symbol}
                      </button>
                    </a>
                  {/if}
                {/if}
```
```svelte
              {#if pie.useMintOverBuy}
                <button on:click={() => {
                  modalOption.token = pie.address;
                  modal.open();
                }} class="table-btn highlight-box min-w-70px">
                  {pie.symbol}
                </button>
              {:else}
                <a href={`#/swap`}>
                  <button class="table-btn highlight-box min-w-70px">
                    {pie.symbol}
                  </button>
                </a>
              {/if}
```
 ```svelte
                 {#if pie.buyButton}
                  {#if pie.useMintOverBuy}
                      <a href={pie.symbol == "SLICE" ? '#/slice' : `#/pie/${pie.address}`}>
                        <button class="table-btn highlight-box min-w-70px">
                          {pie.symbol}
                        </button>
                      </a>
                  {:else}
                    <a href={`#/swap`}>
                      <button class="table-btn highlight-box min-w-70px">
                        {pie.symbol}
                      </button>
                    </a>
                  {/if}
                {/if}
```

In summary: it appears to me to be absolutely fine to make this change, enabling the wider functionality

2022-06-06 11:06 UTC, Alexintosh commented
Change DAI with USDC, check decimals

2022-06-08 13:05 UTC, gbonumore approved these changes

2022-06-08 13:38 UTC, AdrianAddesso requested changes
Almost there. One issue found.

**Fix needed**
❌  DEFI++ goes to exchange page <- It does, but the exchange does not Show DeFi++ listed when accessed from the PiePage

**Passed testing**
✅  PLAY goes to Sushiswap
✅  BCP goes to BCP page where the modal can be opened
✅  Exchange defaults to buying DOUGH 
✅  Exchange has swapped DAI for USDC + check with decimals
✅ DEFI++ added to exchange page

2022-06-08 13:50 UTC, AdrianAddesso approved these changes
Approved. All working as expected.

✅  PLAY goes to Sushiswap
✅  DEFI++ goes to exchange page <- It does, but the exchange does not Show DeFi++ listed when accessed from the PiePage
✅  BCP goes to BCP page where the modal can be opened
✅  Exchange defaults to buying DOUGH 
✅  Exchange has swapped DAI for USDC + check with decimals
✅ DEFI++ added to exchange page

2022-06-08 13:56 UTC, merged